version: '1'

services:
    web:
            container_name: web
            build: .
            command: >                
                bash -c "
                python3 -m pip install virtualenv                
                && python -m venv env && ls
                && chmod +x ./env/bin/activate && ./env/bin/activate
                && pip install -r requirements.txt
                && ls
                && python manage.py makemigrations 
                && python manage.py migrate
                && python manage.py createsuperuser
                && python manage.py runserver 0.0.0.0:8000"
            volumes:
                - pgdata:/code
            ports:
                - 80:8000
            depends_on:
                - db

    db: 
        image: postgres
        container_name: db
        environment: 
            - POSTGRES_USER=test 
            - POSTGRES_PASSWORD=password 
            - POSTGRES_DB=studentdb
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
          - pgdata:/var/lib/postgres/data

volumes:
   pgdata:



    